path:
  train_path: ../dataset/train/train_final.csv
  dev_path: ../dataset/train/dev_final.csv
  test_path: ../dataset/test/test_final.csv

model:
  model_name: klue/roberta-large
  last_dense_layer_dropout_prob: 0.1
  max_seq_length: 256
  alpha: 0.25
  gamma: 2
  custom_model: 2


train:
  epochs: 10
  batch_size: 32
  learning_rate: 5e-5
  save_steps: 0
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 50
  eval_steps: 250
  fp16: True
  gradient_accumulation_steps: 2

utils:
  seed: 42
  top_k : 5

wandb:
  project_name: shingeun
  curr_ver: shingeun_final

