path:
  train_path: ../dataset/train/train_final.csv
  dev_path: ../dataset/train/dev_final.csv
  test_path: ../dataset/test/test_final.csv

model:
  model_name: klue/roberta-large

train:
  epochs: 10
  batch_size: 64
  learning_rate: 8.004650990712485e-05
  save_steps: 1000
  warmup_steps: 347
  weight_decay: 0.09746789183642092
  logging_steps: 1000
  eval_steps: 1000

utils:
  seed: 42
  top_k : 5

wandb:
  project_name: rlarlgh96