path:
  train_path: ../dataset/train/train.csv
  dev_path: ../dataset/train/dev.csv
  test_path: ../dataset/test/test_data.csv
  tapt_model_path: ./tapt/klue_roberta_large

model:
  model_name: klue/roberta-large
  use_tapt_model: False

train:
  epochs: 20
  batch_size: 64
  learning_rate: 2e-5
  save_steps: 500
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  eval_steps: 500
  fp16: True

utils:
  seed: 42
  top_k : 5

wandb:
  project_name: level2_RE