path:
  train_path: ../dataset/train/train.csv
  dev_path: ../dataset/train/dev.csv
  test_path: ../dataset/test/test_data.csv

model:
  model_name: klue/roberta-large

train:
  epochs: 20
  batch_size: 32
  learning_rate: 2e-5
  save_steps: 2000
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 2000
  eval_steps: 500
  fp16: True

utils:
  seed: 42
  top_k : 3

wandb:
  project_name: level2_RE